services:
  - type: web
    name: stem-separator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MAX_FILE_SIZE_MB
        value: 100
      - key: CLEANUP_INTERVAL_HOURS
        value: 2
      - key: TEMP_DIR_MAX_SIZE_GB
        value: 1
    disk:
      name: temp-storage
      mountPath: /tmp/audio_processing
      sizeGB: 1 